name: 24/7 Monitor
on:
  schedule:
    - cron: '*/5 * * * *' # Chạy mỗi 5 phút
  workflow_dispatch:      # Cho phép bấm chạy thủ công

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install curl_cffi
      - run: python monitor.py
